name: Pytest

on: [push]

jobs:
  test_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install package
        run: |
          python -m pip install --no-deps .
      - name: Install dev requirements
        run: |
          python -m pip install -r dev-requirements.txt
      - name: Test with pytest
        if: ${{ always() }}
        run: |
          python -m pytest -sv --show-capture=no tests
